// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type EmailInput struct {
	Account  string `json:"account"`
	Pass     string `json:"pass"`
	Tags     string `json:"tags"`
	Assigned string `json:"assigned"`
	Read     string `json:"read"`
	Method   string `json:"method"`
}

type Mutation struct {
}

type NewTodo struct {
	Text   string `json:"text"`
	UserID string `json:"userId"`
}

type Query struct {
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
